// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoQFP4IuHoSLmqmFxAGCutp-Ir2bJyP-Q',
    appId: '1:716802995665:web:ab44e844045fe10720dcf0',
    messagingSenderId: '716802995665',
    projectId: 'oscar-meds-2026',
    authDomain: 'oscar-meds-2026.firebaseapp.com',
    storageBucket: 'oscar-meds-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfLEUseXVeyvNrDBWNlTx5aC-tJIfGexA',
    appId: '1:716802995665:android:fa3aa2c77d98d94e20dcf0',
    messagingSenderId: '716802995665',
    projectId: 'oscar-meds-2026',
    storageBucket: 'oscar-meds-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCF2cR0xvZUjq0rzvz5X_XmQyjNvyAXa8',
    appId: '1:716802995665:ios:45d880f244727ef120dcf0',
    messagingSenderId: '716802995665',
    projectId: 'oscar-meds-2026',
    storageBucket: 'oscar-meds-2026.firebasestorage.app',
    iosBundleId: 'com.example.myMedTracker',
  );
}
